import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { useState, useEffect } from "react";
import MyHeader from "../components/header";
import HomeScreen from "../components/homeScreen";
import { showInfo } from "../components/signals";

const mapboxgl = require("mapbox-gl/dist/mapbox-gl.js");

mapboxgl.accessToken =
  "pk.eyJ1IjoicGllcnJlYW50b25hIiwiYSI6ImNrendwdjB1ajAyM2wyb3J2b2JwbzhmeGQifQ.ChHYu8fw2OwFONdoG7PPAw";

export default function Home() {
  const [pageIsMounted, setPageIsMounted] = useState(false);
  const [HUD, setHUD] = useState(false);

  const refresh = () => {
    setHUD(true);
  }

  useEffect(() => {
    const showHUD = showInfo.add(refresh);
    return () => {
      showInfo.detach(showHUD);
    };
  });

  useEffect(() => {
    setPageIsMounted(true);

    const plage1 = [12.554729, 55.70651];
    const plage2 = [8.65147, 55.608166];
    const plage3 = [8.65147, 40.608166];

    const map = new mapboxgl.Map({
      container: "my-map",
      style: "mapbox://styles/pierreantona/ckzwt8772000514pbxx4nxm3f",
      center: plage1,
      zoom: 3,
    });

    // create the popup
    const popup = new mapboxgl.Popup({ offset: 25 }).setText(
      "Construction on the Washington Monument began in 1848."
    );

    const popup2 = new mapboxgl.Popup({ offset: 25 }).setText(
      "Construction on the Washington Monument began in 1848."
    );

    const popup3 = new mapboxgl.Popup({ offset: 25 }).setText(
      "Construction on the Washington Monument began in 1848."
    );

    const el = document.createElement("div");
    el.id = "marker1";

    const el2 = document.createElement("div");
    el2.id = "marker2";

    const el3 = document.createElement("div");
    el3.id = "marker3";

    // Marker plage 1
    new mapboxgl.Marker(el)
      .setLngLat(plage1)
      .setPopup(popup)
      .addTo(map);

    // Marker plage 2
    new mapboxgl.Marker(el2)
      .setLngLat(plage2)
      .setPopup(popup2)
      .addTo(map);

    // Marker plage 3
    new mapboxgl.Marker(el3)
      .setLngLat(plage3)
      .setPopup(popup3) 
      .addTo(map);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>The Sea Cleaners - Maps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css"
          rel="stylesheet"
        />
        <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.min.js'></script>
        <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.css' type='text/css' />
      </Head>

      <MyHeader />
      <main className={styles.main}>
        <HomeScreen />
        <div id="my-map" className={styles.mymap} />
      </main>
    </div>
  );
}
