import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";

const mapboxgl = require("mapbox-gl/dist/mapbox-gl.js");

mapboxgl.accessToken =
  "pk.eyJ1IjoicGllcnJlYW50b25hIiwiYSI6ImNrendwdjB1ajAyM2wyb3J2b2JwbzhmeGQifQ.ChHYu8fw2OwFONdoG7PPAw";

export default function Home() {
  
const [pageIsMounted, setPageIsMounted] = useState(false);

  useEffect(() => {
    setPageIsMounted(true)
      const map = new mapboxgl.Map({
        container: "my-map",
        style: "mapbox://styles/pierreantona/ckzwt8772000514pbxx4nxm3f",
      });
}, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <div id="my-map" style={{width:'100%', height: 500}}/>
      </main>
    </div>
  );
}
